### PR TITLE
Add didSet to secondaryCalloutActionProvider in ObservableKeyboardContext

### PR DESCRIPTION
**Pull request by Brennanium**
Based on [this](https://github.com/danielsaidi/KeyboardKit/issues/165#issue-785624875) issue.

### CODE REVIEW

**Review by danielsaidi — APPROVED** [review]
Great, thanks! I will merge this then apply another change 👍

**Comment by danielsaidi** [comment]
Im not sure about having that shared context, but until we change it I just made the provider and context settable, so that `didSet` can just update the provider:

```
@Published public var secondaryCalloutActionProvider: SecondaryCalloutActionProvider {
    didSet { SecondaryInputCalloutContext.shared.actionProvider = secondaryCalloutActionProvider }
}    
```

This is probably more correct than to set a whole new shared context, in case someone has injected a custom one. However, then this is probably not a good idea either, since the shared context may have a deliberately set provider which we then flush.

I will probably clean this up before 4.0.

**Comment by Brennanium** [comment]
Sounds good to me!  Yeah making a whole new context every time was overkill oops 😅

**Comment by danielsaidi** [comment]
I actually decided to entirely remove `secondaryCalloutActionProvider` from the keyboard context.

I have run into problems with having all these services and providers in the context, since many of them depend on the context, which can lead to a circular dependency. I will most probably remove them from the context later on.

**Pull request merged**
